POST http://localhost:5000/api/recipe/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmU5MWYyYWNhZGJkNjQzNzA0YmIwODQiLCJlbWFpbCI6InJ5YW5ub2dyYWxlcy4wMjUuZ3RzaUBnbWFpbC5jb20iLCJ0eXBlIjoiVXNlcjpSZWd1bGFyIiwiZnVsbE5hbWUiOiJyeWFuIG5vZ3JhbGVzIiwiZGF0ZSI6IjIwMjAtMTItMjdUMjM6NTY6MjYuNzU1WiIsImlhdCI6MTYwOTgwNjQzM30.heQvIfGmHSmVtEfq8iacKD1e2GBvFyWj6MA7Dg1p45w

{
    "foodName": "Toasted pineapple bread",
    "goodFor": "50",
    "readyIn" : "3 Hours",
    "foodImages": ["Image-2.jpg"],
    "tags": [
        {
            "tagName": "Meaty",
            "color": "#fff324"
        },
        {
            "tagName": "Meaty",
            "color": "#fff324"
        },
        {
            "tagName": "Meaty",
            "color": "#fff324"
        },
        {
            "tagName": "Meaty",
            "color": "#fff512"
        }
    ],
    "ingredients": [
        {
            "name": "Alpurpose flour remix",
            "amount": "5",
            "unit": "kg",
            "price": "300"
        },
        {
            "name": "Nestle Krema Kondensada",
            "amount": "2",
            "unit": "cup",
            "price": "70"
        },
        {
            "name": "Pork Meat",
            "amount": "2",
            "unit": "kg",
            "price": "300"
        },
        {
            "name": "Sprite",
            "amount": "3",
            "unit": "Cups",
            "price": "50"
        },
        {
            "name": "Sesame Seeds",
            "amount": "1",
            "unit": "pack",
            "price": "10"
        }
    ],
    "instruction": ["Test"],
    "nutrition": {
        "totalCalories": "200",
        "caloricBreakDown": {
            "percentProtein": "200",
            "percentFat": "200",
            "percentCarbs": "200"
        }
    },
    "ownerInfo": {
        "id": "5fe91f2acadbd643704bb084",
        "name": "ryan nograles"
    }
}

###

GET  http://localhost:5000/api/recipe/read-all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmU5MWYyYWNhZGJkNjQzNzA0YmIwODQiLCJlbWFpbCI6InJ5YW5ub2dyYWxlcy4wMjUuZ3RzaUBnbWFpbC5jb20iLCJ0eXBlIjoiVXNlcjpSZWd1bGFyIiwiZnVsbE5hbWUiOiJyeWFuIG5vZ3JhbGVzIiwiZGF0ZSI6IjIwMjAtMTItMjdUMjM6NTY6MjYuNzU1WiIsImlhdCI6MTYwOTgwNjQzM30.heQvIfGmHSmVtEfq8iacKD1e2GBvFyWj6MA7Dg1p45w

###

DELETE   http://localhost:5000/api/recipe/delete/600925c9f696f525b04f679b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmU5MWYyYWNhZGJkNjQzNzA0YmIwODQiLCJlbWFpbCI6InJ5YW5ub2dyYWxlcy4wMjUuZ3RzaUBnbWFpbC5jb20iLCJ0eXBlIjoiVXNlcjpSZWd1bGFyIiwiZnVsbE5hbWUiOiJyeWFuIG5vZ3JhbGVzIiwiZGF0ZSI6IjIwMjAtMTItMjdUMjM6NTY6MjYuNzU1WiIsImlhdCI6MTYwOTgwNjQzM30.heQvIfGmHSmVtEfq8iacKD1e2GBvFyWj6MA7Dg1p45w
